//   LOADER

export const LOADER = "LOADER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const CURRENT_USER_DETAIL = "CURRENT_USER_DETAIL";
//  MessageReducer

export const ERROR_MESSAGE = "ERROR_MESSAGE";
export const SUCCESS_MESSAGE = "SUCCESS_MESSAGE";
export const CLOSE_MESSAGE = "CLOSE_MESSAGE";

// CHAT REDUCER

export const CHAT_OPEN = "CHAT_OPEN";
export const SEND_MESSAGE = "SEND_MESSAGE";

// Search Action
export const SEARCH_RESULT = "SEARCH_RESULT";
export const CLEAR_SEARCH_RESULT = "CLEAR_SEARCH_RESULT";
